#!/bin/sh
echo 'searching for uncensored creds!'
export PATH=$PATH:$(pwd)
export PYTHONPATH=$(pwd)

if [ "$(venv/Scripts/python.exe .githooks/_censor_creds.py)" ]; then
  # config file was changed so api_key isn't exposed.
  # commit those changes
  echo "squashing new commit into intended commit"
  git add .
  git commit -m "hiding creds..."
  git checkout -b hiding-creds
  git checkout master
  git reset --hard HEAD # un-do config.json change from master branch
  git merge --squash hiding-creds
  git branch -D hiding-creds
  echo "done!"
fi