#!/bin/sh
echo 'searching for uncensored creds!'
# script run
export PATH=$PATH:$(pwd)
export PYTHONPATH=$(pwd)
venv/Scripts/python.exe .githooks/_censor_creds.py

if [ $? -eq 1 ]; then
  # config file was changed so api_key isn't exposed.
  # add those changes into the commit
  echo "re-adding config file"
  git add config.json

else
  echo "creds already censored :)"

fi