name: github-linters-CI
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Uri-Yakir/github-linter-CI@master
